//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel_accounting.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int ID { get; set; }
        public int YearExp { get; set; }
        public decimal KF { get; set; }
    }
}
