//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel_accounting.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int RoleID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool isDeleted { get; set; }
        public byte[] Image { get; set; }
        public string Adress { get; set; }
        public int IDPassport { get; set; }
        public int IDEmploymentHistory { get; set; }
        public int IDINN { get; set; }
        public int IDSNILS { get; set; }
        public int IDMilitary { get; set; }
        public int IDMedical { get; set; }
        public int IDEducation { get; set; }
        public int IDPlatform { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual EmploymentHistory EmploymentHistory { get; set; }
        public virtual INN INN { get; set; }
        public virtual Medical Medical { get; set; }
        public virtual Military Military { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Role Role { get; set; }
        public virtual SNILS SNILS { get; set; }
    }
}
